-- MySQL Script generated by MySQL Workbench
-- Mon Sep  5 13:29:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `escuela` ;

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escuela` ;
USE `escuela` ;

-- -----------------------------------------------------
-- Table `escuela`.`materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`materia` ;

CREATE TABLE IF NOT EXISTS `escuela`.`materia` (
  `materia_id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'nombre',
  `version` VARCHAR(45) NOT NULL DEFAULT 'version',
  `grado` INT NOT NULL,
  PRIMARY KEY (`materia_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`Profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`Profesor` ;

CREATE TABLE IF NOT EXISTS `escuela`.`Profesor` (
  `codigo_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'nombre',
  `apellido` VARCHAR(45) NOT NULL DEFAULT 'apellido',
  `materia_materia_id` INT NOT NULL,
  PRIMARY KEY (`codigo_id`),
  INDEX `fk_Profesor_materia1_idx` (`materia_materia_id` ASC) VISIBLE,
  CONSTRAINT `fk_Profesor_materia1`
    FOREIGN KEY (`materia_materia_id`)
    REFERENCES `escuela`.`materia` (`materia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`alumno` ;

CREATE TABLE IF NOT EXISTS `escuela`.`alumno` (
  `alunmo_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL DEFAULT 'nombre',
  `apellido` VARCHAR(45) NOT NULL DEFAULT 'apellido',
  `curso` VARCHAR(45) NOT NULL DEFAULT 'curso',
  PRIMARY KEY (`alunmo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`asignacion profesor-alunmo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`asignacion profesor-alunmo` ;

CREATE TABLE IF NOT EXISTS `escuela`.`asignacion profesor-alunmo` (
  `Profesor_codigo_id` INT NOT NULL,
  `alumno_alunmo_id` INT NOT NULL,
  PRIMARY KEY (`Profesor_codigo_id`, `alumno_alunmo_id`),
  INDEX `fk_Profesor_has_alumno_alumno1_idx` (`alumno_alunmo_id` ASC) VISIBLE,
  INDEX `fk_Profesor_has_alumno_Profesor_idx` (`Profesor_codigo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Profesor_has_alumno_Profesor`
    FOREIGN KEY (`Profesor_codigo_id`)
    REFERENCES `escuela`.`Profesor` (`codigo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesor_has_alumno_alumno1`
    FOREIGN KEY (`alumno_alunmo_id`)
    REFERENCES `escuela`.`alumno` (`alunmo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`asignacion de materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escuela`.`asignacion de materias` ;

CREATE TABLE IF NOT EXISTS `escuela`.`asignacion de materias` (
  `alumno_alunmo_id` INT NOT NULL,
  `materia_materia_id` INT NOT NULL,
  PRIMARY KEY (`alumno_alunmo_id`, `materia_materia_id`),
  INDEX `fk_alumno_has_materia_materia1_idx` (`materia_materia_id` ASC) VISIBLE,
  INDEX `fk_alumno_has_materia_alumno1_idx` (`alumno_alunmo_id` ASC) VISIBLE,
  CONSTRAINT `fk_alumno_has_materia_alumno1`
    FOREIGN KEY (`alumno_alunmo_id`)
    REFERENCES `escuela`.`alumno` (`alunmo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_has_materia_materia1`
    FOREIGN KEY (`materia_materia_id`)
    REFERENCES `escuela`.`materia` (`materia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
